version: '3'

name: training-dev-java-spring

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - .\prometheus\etc:/etc/prometheus
      - .\prometheus\data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - .\grafana\provisioning\datasources:/etc/grafana/provisioning/datasources
      - .\grafana\data:/var/lib/grafana

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - .\redis\data:/data
